using System.Text;

namespace SGOFWS.Templates;

public class StringTemplates
{
	public StringBuilder getTrackingReportTemplate()
	{
		StringBuilder sbuilder = new StringBuilder();
		sbuilder.AppendLine("<!doctype html>");
		sbuilder.AppendLine("<html>");
		sbuilder.AppendLine("<head>");
		sbuilder.AppendLine("<meta charset='ISO-8859-1'>");
		sbuilder.AppendLine("<!-- utf-8 works for most cases -->");
		sbuilder.AppendLine("<meta name='viewport' content='width=device-width, initial-scale=1.0'>");
		sbuilder.AppendLine("<!-- Forcing initial-scale shouldnt be necessary -->");
		sbuilder.AppendLine("<meta http-equiv='X-UA-Compatible' content='IE=edge'>");
		sbuilder.AppendLine("<!-- Use the latest (edge) version of IE rendering engine -->");
		sbuilder.AppendLine("<title>EmailTemplate-Responsive</title>");
		sbuilder.AppendLine("<!-- The title tag shows in email notifications, like Android 4.4. -->");
		sbuilder.AppendLine("<!-- Please use an inliner tool to convert all CSS to inline as inpage or external CSS is removed by email clients -->");
		sbuilder.AppendLine("<!-- important in CSS is used to prevent the styles of currently inline CSS from overriding the ones mentioned in media queries when corresponding screen sizes are encountered -->");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("<!-- CSS Reset -->");
		sbuilder.AppendLine("<style type='text/css'>");
		sbuilder.AppendLine("/* What it does: Remove spaces around the email design added by some email clients. */");
		sbuilder.AppendLine("/* Beware: It can remove the padding / margin and add a background color to the compose a reply window. */");
		sbuilder.AppendLine("html, body {");
		sbuilder.AppendLine("font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif;");
		sbuilder.AppendLine("margin: 0 !important;");
		sbuilder.AppendLine("padding: 0 !important;");
		sbuilder.AppendLine("height: 100% !important;");
		sbuilder.AppendLine("width: 100% !important;");
		sbuilder.AppendLine("}");
		sbuilder.AppendLine("/* What it does: Stops email clients resizing small text. */");
		sbuilder.AppendLine("* {");
		sbuilder.AppendLine("-ms-text-size-adjust: 100%;");
		sbuilder.AppendLine("-webkit-text-size-adjust: 100%;");
		sbuilder.AppendLine("}");
		sbuilder.AppendLine("/* What it does: Forces Outlook.com to display emails full width. */");
		sbuilder.AppendLine(".ExternalClass {");
		sbuilder.AppendLine("width: 100%;");
		sbuilder.AppendLine("}");
		sbuilder.AppendLine("/* What is does: Centers email on Android 4.4 */");
		sbuilder.AppendLine("div[style*='margin: 16px 0'] {");
		sbuilder.AppendLine("margin: 0 !important;");
		sbuilder.AppendLine("}");
		sbuilder.AppendLine("/* What it does: Stops Outlook from adding extra spacing to tables. */");
		sbuilder.AppendLine("table, td {");
		sbuilder.AppendLine("mso-table-lspace: 0pt !important;");
		sbuilder.AppendLine("mso-table-rspace: 0pt !important;");
		sbuilder.AppendLine("}");
		sbuilder.AppendLine("/* What it does: Fixes webkit padding issue. Fix for Yahoo mail table alignment bug. Applies table-layout to the first 2 tables then removes for anything nested deeper. */");
		sbuilder.AppendLine("table {");
		sbuilder.AppendLine("border-spacing: 0 !important;");
		sbuilder.AppendLine("border-collapse: collapse !important;");
		sbuilder.AppendLine("table-layout: fixed !important;");
		sbuilder.AppendLine("margin: 0 auto !important;");
		sbuilder.AppendLine("}");
		sbuilder.AppendLine("table table table {");
		sbuilder.AppendLine("table-layout: auto;");
		sbuilder.AppendLine("}");
		sbuilder.AppendLine("/* What it does: Uses a better rendering method when resizing images in IE. */");
		sbuilder.AppendLine("img {");
		sbuilder.AppendLine("-ms-interpolation-mode: bicubic;");
		sbuilder.AppendLine("}");
		sbuilder.AppendLine("/* What it does: Overrides styles added when Yahoos auto-senses a link. */");
		sbuilder.AppendLine(".yshortcuts a {");
		sbuilder.AppendLine("border-bottom: none !important;");
		sbuilder.AppendLine("}");
		sbuilder.AppendLine("/* What it does: Another work-around for iOS meddling in triggered links. */");
		sbuilder.AppendLine("a[x-apple-data-detectors] {");
		sbuilder.AppendLine("color: inherit !important;");
		sbuilder.AppendLine("}");
		sbuilder.AppendLine("</style>");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("<!-- Progressive Enhancements -->");
		sbuilder.AppendLine("<style type='text/css'>");
		sbuilder.AppendLine("/* What it does: Hover styles for buttons */");
		sbuilder.AppendLine(".button-td,  .button-a {");
		sbuilder.AppendLine("transition: all 100ms ease-in;");
		sbuilder.AppendLine("}");
		sbuilder.AppendLine(".button-td:hover,  .button-a:hover {");
		sbuilder.AppendLine("background: #555555 !important;");
		sbuilder.AppendLine("border-color: #555555 !important;");
		sbuilder.AppendLine("}");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("/* Media Queries */");
		sbuilder.AppendLine(".email-container {");
		sbuilder.AppendLine("width: 100% !important;");
		sbuilder.AppendLine("}");
		sbuilder.AppendLine("/* What it does: Forces elements to resize to the full width of their container. Useful for resizing images beyond their max-width. */");
		sbuilder.AppendLine(".fluid,  .fluid-centered {");
		sbuilder.AppendLine("max-width: 100% !important;");
		sbuilder.AppendLine("height: auto !important;");
		sbuilder.AppendLine("margin-left: auto !important;");
		sbuilder.AppendLine("margin-right: auto !important;");
		sbuilder.AppendLine("/* And center justify these ones. */");
		sbuilder.AppendLine(".fluid-centered {");
		sbuilder.AppendLine("margin-left: auto !important;");
		sbuilder.AppendLine("margin-right: auto !important;");
		sbuilder.AppendLine("}");
		sbuilder.AppendLine("/* What it does: Forces table cells into full-width rows. */");
		sbuilder.AppendLine(".stack-column,  .stack-column-center {");
		sbuilder.AppendLine("display: block !important;");
		sbuilder.AppendLine("width: 100% !important;");
		sbuilder.AppendLine("max-width: 100% !important;");
		sbuilder.AppendLine("direction: ltr !important;");
		sbuilder.AppendLine("}");
		sbuilder.AppendLine("/* And center justify these ones. */");
		sbuilder.AppendLine(".stack-column-center {");
		sbuilder.AppendLine("text-align: center !important;");
		sbuilder.AppendLine("}");
		sbuilder.AppendLine("/* What it does: Generic utility class for centering. Useful for images, buttons, and nested tables. */");
		sbuilder.AppendLine(".center-on-narrow {");
		sbuilder.AppendLine("text-align: center !important;");
		sbuilder.AppendLine("display: block !important;");
		sbuilder.AppendLine("margin-left: auto !important;");
		sbuilder.AppendLine("margin-right: auto !important;");
		sbuilder.AppendLine("float: none !important;");
		sbuilder.AppendLine("}");
		sbuilder.AppendLine("table.center-on-narrow {");
		sbuilder.AppendLine("display: inline-block !important;");
		sbuilder.AppendLine("}");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("}");
		sbuilder.AppendLine("</style>");
		sbuilder.AppendLine("</head>");
		sbuilder.AppendLine("<body bgcolor='#e0e0e0' width='100%' style='margin: 0;' yahoo='yahoo' border='0' cellspacing='0' cellpadding='0' >");
		sbuilder.AppendLine("<table bgcolor='#e0e0e0' cellpadding='0' cellspacing='0' border='0' height='100%' width='100%' style='border-collapse:collapse;'>");
		sbuilder.AppendLine("<tr>");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("<td>");
		sbuilder.AppendLine("<center style='width: 100%;'>");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("<!-- Visually Hidden Preheader Text : BEGIN -->");
		sbuilder.AppendLine("<div style='display:none;font-size:1px;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;mso-hide:all;font-family: sans-serif;'> </div>");
		sbuilder.AppendLine("<!-- Visually Hidden Preheader Text : END -->");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("<!-- Email Header : BEGIN -->");
		sbuilder.AppendLine("<table align='center' width='600' class='email-container'>");
		sbuilder.AppendLine("</table>");
		sbuilder.AppendLine("<!-- Email Header : END -->");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("<!-- Email Body : BEGIN -->");
		sbuilder.AppendLine("<table style='margin-top:0.6em!important;width: 95%!important;' cellspacing='0' cellpadding='0' border='0' align='center' bgcolor='#ffffff' width='600' class='email-container'>");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("<!-- Hero Image, Flush : BEGIN -->");
		sbuilder.AppendLine("<tr>");
		sbuilder.AppendLine("<td width='100%' class='full-width-image'>");
		sbuilder.AppendLine("<img style='padding: 0; margin-left: 0.9em;height='150px!important;width:150px!important;' src='' alt=''>");
		sbuilder.AppendLine("</td>");
		sbuilder.AppendLine("</tr>");
		sbuilder.AppendLine("<!-- Hero Image, Flush : END -->");
		sbuilder.AppendLine("<table><tr><td><h4 style='margin-left:0.7em'>Tracking Report </h4></td> <td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>");
		sbuilder.AppendLine("<td><h3 style='text-align: right;font-family:&quot;Arial&quot;,sans-serif; color: black'>Data: @Model.data</ span ></ h3 ></td></tr></table> ");
		sbuilder.AppendLine("<br>");
		sbuilder.AppendLine("<div style='margin-left:8.4pt'>");
		sbuilder.AppendLine("</div>");
		sbuilder.AppendLine("<tr>");
		sbuilder.AppendLine("<td style='padding: 25px; color:#232222; font-family:Arial, sans-serif; text-align: justify; font-size: 12px'>");
		sbuilder.AppendLine("<br>");
		sbuilder.AppendLine("<div align='center'>");
		sbuilder.AppendLine("  <center>");
		sbuilder.AppendLine("  <table bgcolor='#20ab6c' width='100%' cellSpacing='0' cellPadding='12' border='0' bordercolor='#000000' bordercolordark='#CCFFFF' bordercolorlight='#20ab6c'>");
		sbuilder.AppendLine("    <tr >");
		sbuilder.AppendLine("      <td borderColorLight='#000000' borderColorDark='#000000' width='100%' style='filter:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#000000', endColorStr='#20ab6c', gradientType='0')'><font face='Segoe UI' color='#ffffff' size='4'> ");
		sbuilder.AppendLine("New Consignments");
		sbuilder.AppendLine("</font></td>");
		sbuilder.AppendLine("    </tr>");
		sbuilder.AppendLine("  </table>");
		sbuilder.AppendLine("  </center>");
		sbuilder.AppendLine("</div><br>");
		sbuilder.AppendLine("<div align='center'>");
		sbuilder.AppendLine("<center>");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("<table class='b1' borderColor='#FFFFFF' cellSpacing='1' cellPadding='8' width='100%' bgColor='#FFFFFF' borderColorLight='#DBDBDB' border='0' bordercolordark='#FFFFFF'>");
		sbuilder.AppendLine("<tr>");
		sbuilder.AppendLine("<td  vAlign='bottom' borderColorLight='#C0C0C0' borderColorDark='#FFFFFF'  style='filter:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#FFFFFF', endColorStr='#E4E5ED', gradientType='0')'><font color='#545454' size='2' face='Segoe UI'><b>Consignment Number </b></font></td>");
		sbuilder.AppendLine("<td  vAlign='bottom' borderColorLight='#C0C0C0' borderColorDark='#FFFFFF'  style='filter:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#FFFFFF', endColorStr='#E4E5ED', gradientType='0')'><font color='#545454' size='2' face='Segoe UI'><b>Consignment Type</b></font></td>");
		sbuilder.AppendLine("<td  vAlign='bottom' borderColorLight='#C0C0C0' borderColorDark='#FFFFFF'  style='filter:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#FFFFFF', endColorStr='#E4E5ED', gradientType='0')'><font color='#545454' size='2' face='Segoe UI'><b>Data</b></font></td>");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("</tr>");
		sbuilder.AppendLine("@foreach (var consignacao in Model.novasConsignacoes)");
		sbuilder.AppendLine("{");
		sbuilder.AppendLine("<tr  bgcolor=#fbfdfd color=#545454 onmouseover='this.style.backgroundColor='#FFFFFF'' onmouseout='this.style.backgroundColor='#fbfdfd'' >");
		sbuilder.AppendLine("<td valign='top'><font color='#545454' face='Segoe UI' size='2'>@consignacao.bo3.UConsgno</font></td>");
		sbuilder.AppendLine("<td valign='top'><font color='#545454' face='Segoe UI' size='2'>@consignacao.bo3.UConsgtip</font></td>");
		sbuilder.AppendLine("<td valign='top'><font color='#545454' face='Segoe UI' size='2'>@consignacao.bo.Dataobra</font></td>");
		sbuilder.AppendLine("</tr>");
		sbuilder.AppendLine("}");
		sbuilder.AppendLine("<tr  bgcolor=#fbfdfd color=#545454 onmouseover='this.style.backgroundColor='#FFFFFF'' onmouseout='this.style.backgroundColor='#fbfdfd'' >");
		sbuilder.AppendLine("<td valign='top' ><font color='#545454' face='Segoe UI' size='2'>&nbsp;</font></td>");
		sbuilder.AppendLine("<td valign='top' ><font color='#545454' face='Segoe UI' size='2'>&nbsp;</font></td>");
		sbuilder.AppendLine("<td valign='top' ><font color='#545454' face='Segoe UI' size='2'>&nbsp;</font></td>");
		sbuilder.AppendLine("<td valign='top'   ><font color='#545454' face='Segoe UI' size='2'>Total</font></td>");
		sbuilder.AppendLine("<td valign='top'   ><font color='#545454' face='Segoe UI' size='2'>@Model.totalNovasConsignacoes</font></td>");
		sbuilder.AppendLine("</tr>");
		sbuilder.AppendLine("</table>");
		sbuilder.AppendLine("  </center>");
		sbuilder.AppendLine("</div>");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("<p>&nbsp;</p>");
		sbuilder.AppendLine("<br>");
		sbuilder.AppendLine("<div align='center'>");
		sbuilder.AppendLine("  <center>");
		sbuilder.AppendLine("  <table bgcolor='#d70808' width='100%' cellSpacing='0' cellPadding='12' border='0' bordercolor='#000000' bordercolordark='#CCFFFF' bordercolorlight='#d70808'>");
		sbuilder.AppendLine("    <tr >");
		sbuilder.AppendLine("      <td borderColorLight='#000000' borderColorDark='#000000' width='100%' style='filter:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#000000', endColorStr='#20ab6c', gradientType='0')'><font face='Segoe UI' color='#ffffff' size='4'> ");
		sbuilder.AppendLine("Wagons status updated");
		sbuilder.AppendLine("</font></td>");
		sbuilder.AppendLine("    </tr>");
		sbuilder.AppendLine("  </table>");
		sbuilder.AppendLine("  </center>");
		sbuilder.AppendLine("</div><br>");
		sbuilder.AppendLine("<div align='center'>");
		sbuilder.AppendLine("<center>");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("<table class='b1' borderColor='#FFFFFF' cellSpacing='1' cellPadding='8' width='100%' bgColor='#FFFFFF' borderColorLight='#DBDBDB' border='0' bordercolordark='#FFFFFF'>");
		sbuilder.AppendLine("<tr>");
		sbuilder.AppendLine("<td  vAlign='bottom' borderColorLight='#C0C0C0' borderColorDark='#FFFFFF'  style='filter:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#FFFFFF', endColorStr='#E4E5ED', gradientType='0')'><font color='#545454' size='2' face='Segoe UI'><b>Consignment Nº </b></font></td>");
		sbuilder.AppendLine("<td  vAlign='bottom' borderColorLight='#C0C0C0' borderColorDark='#FFFFFF'  style='filter:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#FFFFFF', endColorStr='#E4E5ED', gradientType='0')'><font color='#545454' size='2' face='Segoe UI'><b>Wagon Number</b></font></td>");
		sbuilder.AppendLine("<td  vAlign='bottom' borderColorLight='#C0C0C0' borderColorDark='#FFFFFF'  style='filter:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#FFFFFF', endColorStr='#E4E5ED', gradientType='0')'><font color='#545454' size='2' face='Segoe UI'><b>Wagon Type</b></font></td>");
		sbuilder.AppendLine("<td  vAlign='bottom' borderColorLight='#C0C0C0' borderColorDark='#FFFFFF'  style='filter:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#FFFFFF', endColorStr='#E4E5ED', gradientType='0')'><font color='#545454' size='2' face='Segoe UI'><b>Wagon Mass</b></font></td>");
		sbuilder.AppendLine("<td  vAlign='bottom' borderColorLight='#C0C0C0' borderColorDark='#FFFFFF'  style='filter:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#FFFFFF', endColorStr='#E4E5ED', gradientType='0')'><font color='#545454' size='2' face='Segoe UI'><b>ETA</b></font></td>");
		sbuilder.AppendLine("<td  vAlign='bottom' borderColorLight='#C0C0C0' borderColorDark='#FFFFFF'  style='filter:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#FFFFFF', endColorStr='#E4E5ED', gradientType='0')'><font color='#545454' size='2' face='Segoe UI'><b>Last reported date time</b></font></td>");
		sbuilder.AppendLine("<td  vAlign='bottom' borderColorLight='#C0C0C0' borderColorDark='#FFFFFF'  style='filter:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#FFFFFF', endColorStr='#E4E5ED', gradientType='0')'><font color='#545454' size='2' face='Segoe UI'><b>Last update time stamp</b></font></td>");
		sbuilder.AppendLine("<td  vAlign='bottom' borderColorLight='#C0C0C0' borderColorDark='#FFFFFF'  style='filter:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#FFFFFF', endColorStr='#E4E5ED', gradientType='0');text-align: left;'><font color='#545454' size='2' face='Segoe UI'><b>Status</b></font></td>");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("</tr>");
		sbuilder.AppendLine("@foreach (var vagao in Model.vagoesActualizados)");
		sbuilder.AppendLine("{");
		sbuilder.AppendLine("<tr  bgcolor=#fbfdfd color=#545454 onmouseover='this.style.backgroundColor='#FFFFFF'' onmouseout='this.style.backgroundColor='#fbfdfd'' >");
		sbuilder.AppendLine("<td valign='top'><font color='#545454' face='Segoe UI' size='2'>@vagao.Consgno</font></td>");
		sbuilder.AppendLine("<td valign='top'><font color='#545454' face='Segoe UI' size='2'>@vagao.UVagno</font></td>");
		sbuilder.AppendLine("<td valign='top'><font color='#545454' face='Segoe UI' size='2'>@vagao.UVagtip</font></td>");
		sbuilder.AppendLine("<td valign='top'><font color='#545454' face='Segoe UI' size='2'>@vagao.UPeso</font></td>");
		sbuilder.AppendLine("<td valign='top'><font color='#545454' face='Segoe UI' size='2'>@vagao.UEta</font></td>");
		sbuilder.AppendLine("<td valign='top'><font color='#545454' face='Segoe UI' size='2'>@vagao.UUltdtrep</font></td>");
		sbuilder.AppendLine("<td valign='top'><font color='#545454' face='Segoe UI' size='2'>@vagao.UUltmtmst</font></td>");
		sbuilder.AppendLine("<td valign='top'><font color='#545454' face='Segoe UI' size='2'>@vagao.UStatus</font></td>");
		sbuilder.AppendLine("</tr>");
		sbuilder.AppendLine("}");
		sbuilder.AppendLine("<tr  bgcolor=#fbfdfd color=#545454 onmouseover='this.style.backgroundColor='#FFFFFF'' onmouseout='this.style.backgroundColor='#fbfdfd'' >");
		sbuilder.AppendLine("<td valign='top'><font color='#545454' face='Segoe UI' size='2'>&nbsp;</font></td>");
		sbuilder.AppendLine("<td valign='top'><font color='#545454' face='Segoe UI' size='2'>&nbsp;</font></td>");
		sbuilder.AppendLine("<td valign='top'><font color='#545454' face='Segoe UI' size='2'>&nbsp;</font></td>");
		sbuilder.AppendLine("<td valign='top'><font color='#545454' face='Segoe UI' size='2'>&nbsp;</font></td>");
		sbuilder.AppendLine("<td valign='top'><font color='#545454' face='Segoe UI' size='2'>&nbsp;</font></td>");
		sbuilder.AppendLine("<td valign='top'><font color='#545454' face='Segoe UI' size='2'>Total</font></td>");
		sbuilder.AppendLine("<td valign='top'><font color='#545454' face='Segoe UI' size='2'>Total</font></td>");
		sbuilder.AppendLine("<td valign='top'><font color='#545454' face='Segoe UI' size='2'>Total</font></td>");
		sbuilder.AppendLine("<td valign='top'><font color='#545454' face='Segoe UI' size='2'>@Model.totalVagoesActualizados</font></td>");
		sbuilder.AppendLine("</tr>");
		sbuilder.AppendLine("</table>");
		sbuilder.AppendLine("  </center>");
		sbuilder.AppendLine("</div>");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("<p>&nbsp;</p>");
		sbuilder.AppendLine("<span style='font-size:8.5pt;font-family:&quot;Segoe UI&quot;,sans-serif;color:#232222'><br>");
		sbuilder.AppendLine("<br>");
		sbuilder.AppendLine("Este email é gerado automaticamente pelo Software PHC, caso tenha alguma dúvida por favor contacte-nos pelos telefones +258 21 358 400 | 84 100 7001/2 ou");
		sbuilder.AppendLine("<a href='mailto:suporte@2business.co.mz' target='_blank'>suporte@2business.co.mz</a>.<u></u><u></u></span>");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("<br><br>");
		sbuilder.AppendLine("<span style='font-size:7.0pt;font-family:&quot;Segoe UI&quot;,sans-serif;color:#232222'><br>");
		sbuilder.AppendLine("<br>");
		sbuilder.AppendLine("AVISO LEGAL: Esta mensagem é confidencial e dirigida apenas ao destinatário.<br>");
		sbuilder.AppendLine("Se a recebeu por erro solicitamos que o comunique ao remetente e a elimine<br>");
		sbuilder.AppendLine("assim como qualquer documento anexo. Não há renúncia à confidencialidade<br>");
		sbuilder.AppendLine("nem a nenhum privilégio devido a erro de transmissão.<u></u><u></u></span>");
		sbuilder.AppendLine("  <br>");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("</td>");
		sbuilder.AppendLine("</tr>");
		sbuilder.AppendLine("<!-- 1 Column Text : BEGIN -->");
		sbuilder.AppendLine(" ");
		sbuilder.AppendLine("<!-- Background Image with Text : BEGIN -->");
		sbuilder.AppendLine("<tr>");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("<!--<td width='100%' class='full-width-image'><img src='' width='600'  border='0' align='center' style='width: 100%; max-width: 600px; height: auto;'></td>-->");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("</td>");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("</tr>");
		sbuilder.AppendLine(" ");
		sbuilder.AppendLine("</table>");
		sbuilder.AppendLine("</center>");
		sbuilder.AppendLine("</td>");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("</tr>");
		sbuilder.AppendLine("");
		sbuilder.AppendLine("</table>");
		sbuilder.AppendLine("</body>");
		sbuilder.AppendLine("</html>");
		return sbuilder;
	}
}
